# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#default: &default
#  adapter:  mysql
#  pool: 5
#  timeout: 5000
#  username: root
#  password: E4Fproduction

default: &default
  adapter:  mysql
  encoding:  utf8
  pool: 5
  port:       <%=ENV['3306']%>
  host:       <%=ENV['127.5.182.2']%>
  password:   <%=ENV['TrzLLkw9-HjB']%>
  IDENT:      <%=ENV['redhat:mysql:5.5:0.2.17']%>
  username:   <%=ENV['adminYk5lfW5']%>
  socket:     <%=ENV['/var/lib/openshift/542d71e55973ca383d00050c/mysql//socket/mysql.sock']%>
  database:   <%=ENV['mysql://adminYk5lfW5:TrzLLkw9-HjB@127.5.182.2:3306/']%>

development:
  <<: *default
  pool: 5
  timeout: 5000
  port:       <%=ENV['3306']%>
  host:       <%=ENV['127.5.182.2']%>
  password:   <%=ENV['TrzLLkw9-HjB']%>
  IDENT:      <%=ENV['redhat:mysql:5.5:0.2.17']%>
  username:   <%=ENV['adminYk5lfW5']%>
  socket:     <%=ENV['/var/lib/openshift/542d71e55973ca383d00050c/mysql//socket/mysql.sock']%>
  database:   <%=ENV['mysql://adminYk5lfW5:TrzLLkw9-HjB@127.5.182.2:3306/']%>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test:
  <<: *default
  database: db_test
  pool: 5
  timeout: 5000
  port:       <%=ENV['3306']%>
  host:       <%=ENV['127.5.182.2']%>
  password:   <%=ENV['TrzLLkw9-HjB']%>
  IDENT:      <%=ENV['redhat:mysql:5.5:0.2.17']%>
  username:   <%=ENV['adminYk5lfW5']%>
  socket:     <%=ENV['/var/lib/openshift/542d71e55973ca383d00050c/mysql//socket/mysql.sock']%>
  database:   <%=ENV['mysql://adminYk5lfW5:TrzLLkw9-HjB@127.5.182.2:3306/']%>

production:
  adapter:  mysql
  encoding:  utf8
  pool: 5
  port:       <%=ENV['3306']%>
  host:       <%=ENV['127.5.182.2']%>
  password:   <%=ENV['TrzLLkw9-HjB']%>
  IDENT:      <%=ENV['redhat:mysql:5.5:0.2.17']%>
  username:   <%=ENV['adminYk5lfW5']%>
  socket:     <%=ENV['/var/lib/openshift/542d71e55973ca383d00050c/mysql//socket/mysql.sock']%>
  database:   <%=ENV['mysql://adminYk5lfW5:TrzLLkw9-HjB@127.5.182.2:3306/']%>
