# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16ab82126c90d92464d48fb7eb319542285d5152efaf47a4b23d25d76eaf2b7a4a5b0e346832993a687480a0e9f252c5a157c387f51ce57397b22de0012e1bbf

test:
  secret_key_base: 813e0a3d17cd65243701d77d05a33f9467743542f576392ed1b6cb306fc73b97b4fa2ab65e8416fbe8b2d1228f59d3519d15dfa427b764a83860aff31fc01994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
